# Generated by Django 2.1.2 on 2018-11-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('o_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='o_currency', to='converter.Currency')),
                ('t_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t_currency', to='converter.Currency')),
            ],
        ),
    ]
